import re

emoji_map = {
    '??': 'calendar_month',
    '??': 'group',
    '??': 'attach_money',
    '??': 'credit_card',
    '?': 'check_circle',
    '?': 'cancel',
    '?????': 'school',
    '?????': 'school',
    '??': 'rocket_launch',
    '??': 'payments',
    '??': 'description',
    '??': 'schedule',
    '??': 'edit_document',
    '??': 'bar_chart',
    '??': 'emoji_events',
    '??': 'star',
    '??': 'smartphone',
    '??': 'laptop_mac',
    '??': 'psychology',
    '??': 'palette',
    '??': 'apartment',
    '??': 'push_pin',
    '??': 'warning',
    '??': 'notifications',
    '??': 'edit',
    '???': 'delete',
    '??': 'search',
    '??': 'school',
    '??': 'face',
    '??': 'face_3',
    '??': 'person',
    '??': 'person_4',
    '??': 'celebration',
    '??': 'trending_up',
    '??': 'trending_down',
    '??': 'local_fire_department',
    '??': 'settings',
    '??': 'lock_open',
    '??': 'lock',
    '?': 'help',
    '??': 'pan_tool',
    '??': 'assignment',
    '??': 'lab_profile',
    '??': 'chat',
    '??': 'call',
    '??': 'mail',
    '??': 'link',
    '?????': 'school',
    '?????': 'school',
    '?????': 'school',
    '??': 'payments',
    '??': 'receipt',
    '??': 'menu_book',
    '??': 'draw',
    '???': 'build',
    '???': 'security',
    '??': 'thumb_up',
    '??': 'thumb_down',
    '?': 'auto_awesome',
    '??': 'photo_camera',
    '??': 'photo_camera',
    '???': 'image',
    '???': 'print',
    '??': 'home',
    '??': 'door_front',
    '??': 'key',
    '??': 'language',
    '??': 'lunch_dining',
    '??': 'nutrition',
    '??': 'stethoscope',
    '??': 'healing',
    '??': 'directions_bus',
    '??': 'directions_car',
    '??': 'pedal_bike',
    '??': 'directions_walk',
    '??': 'campaign',
    '??': 'volume_up',
    '??': 'volume_off',
    '??': 'music_note',
    '??': 'movie',
    '??': 'theater_comedy',
    '?': 'sports_soccer',
    '??': 'sports_basketball',
    '??': 'sports_football',
    '??': 'sports_tennis',
    '??': 'emoji_events',
    '??': 'military_tech',
    '???': 'military_tech',
    '??': 'military_tech',
    '??': 'military_tech',
    '??': 'military_tech',
    '??': 'emergency',
    '??': 'traffic',
    '??': 'construction',
    '??': 'stop_circle',
    '?': 'check_circle',
    '?': 'cancel',
    '??': 'check',
    '??': 'close',
    '?': 'add',
    '?': 'remove',
    '?': 'divide',
    '??': 'equal',
    '??': '100',
    '??': '123',
    '??': 'abc',
    '??': 'abc',
    '???': 'font_download',
    '???': 'font_download',
    '??': 'font_download',
    '???': 'font_download',
    '??': 'sos',
    '??': 'arrow_upward',
    '??': 'ac_unit',
    '??': 'money_off',
    '??': 'new_releases',
    '??': 'block',
    '??': 'thumb_up',
    '??': 'compare',
    '??': 'place',
    '???': 'room_service',
    '??': 'event_seat',
    '??': 'group',
    '??': 'group',
    '??': 'check',
    '??': 'close',
    '??': 'fact_check',
    '??': 'storefront',
    '???': 'calendar_month',
    '??': 'discount',
    '??': 'block',
    '??': 'school',
}

with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

def replace_emoji(match):
    emoji = match.group(0)
    icon_name = emoji_map.get(emoji)
    if icon_name:
        return f'<span class="material-symbols-outlined" style="font-size:inherit;vertical-align:-2px;">{icon_name}</span>'
    return emoji

# Create a regex pattern that matches any of the keys in emoji_map
# Sort keys by length descending to match longest first (e.g., ????? before ??)
sorted_emojis = sorted(emoji_map.keys(), key=len, reverse=True)
pattern = re.compile('|'.join(map(re.escape, sorted_emojis)))

new_content = pattern.sub(replace_emoji, content)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Replacement complete.")
